spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"