spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

server:
  port: 8881
  ssl:
      enabled: true
      key-store: src/main/resources/security/cert.p12
      key-store-password: password
      key-store-type: PKCS12
      key-alias: cert

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"